# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iSteer' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iSteer
pod 'BIZPopupView' 
pod 'IQKeyboardManager'
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'UIScrollView-InfiniteScroll'
pod 'SDWebImage', '~>3.8'
pod 'CZPicker'
  target 'iSteerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iSteerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
